#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - path: /etc/yum.repos.d/pgdg.repo
    permissions: 0644
    owner: root
    content: |
      [pgdg13]
      name=PostgreSQL 13 for RHEL/CentOS 7 - x86_64
      baseurl=https://download.postgresql.org/pub/repos/yum/13/redhat/rhel-7-x86_64
      enabled=1
      gpgcheck=0

runcmd:

  # update
  - echo "Starting CloudInit userdata"
  - yum update -y

  # install tools
  - amazon-linux-extras install -y epel
  - yum install postgresql13 oracle-instantclient-basic oracle-instantclient-sqlplus -y
